AllCops:
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'Vagrantfile'
    - 'db/schema.rb'
    - 'config/**/*'
Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 128

Metrics/ClassLength:
  Max: 128

Metrics/AbcSize:
  Max: 24
